// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 9
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){
var m=this,ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},ca=null;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var da=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,ea=function(a){if(null==a)return String(a);var b=da.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},fa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ga=function(a){if(!a||"object"!=ea(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!fa(a,"constructor")&&!fa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var c in a);return void 0===
c||fa(a,c)},ia=function(a,b){var c=b||("array"==ea(a)?[]:{}),d;for(d in a)if(fa(a,d)){var e=a[d];"array"==ea(e)?("array"!=ea(c[d])&&(c[d]=[]),c[d]=ia(e,c[d])):ga(e)?(ga(c[d])||(c[d]={}),c[d]=ia(e,c[d])):c[d]=e}return c};var ja=function(){},w=function(a){return"function"==typeof a},A=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ka=function(a){return"number"==ea(a)&&!isNaN(a)},la=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ma=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},C=function(a){return Math.round(Number(a))||0},na=function(a){var b=[];if(A(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));
return b},F=function(){return new Date},oa=function(a,b){if(!ka(a)||!ka(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},pa=function(){this.prefix="gtm.";this.na={}};pa.prototype.set=function(a,b){this.na[this.prefix+a]=b};pa.prototype.get=function(a){return this.na[this.prefix+a]};pa.prototype.contains=function(a){return void 0!==this.get(a)};
var qa=function(a,b,c){try{return a["19"](a,b||ja,c||ja)}catch(d){}return!1},sa=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ma(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},ta=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},ua=function(a){for(var b=0;b<a.length;b++)a[b]()},va=F().getTime(),wa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c};var G=window,H=document,xa=navigator,I=function(a,b){var c=G[a],d="var "+a+";";if(m.execScript)m.execScript(d,"JavaScript");else if(m.eval)if(null==ca&&(m.eval("var _et_ = 1;"),"undefined"!=typeof m._et_?(delete m._et_,ca=!0):ca=!1),ca)m.eval(d);else{var e=m.document,f=e.createElement("script");f.type="text/javascript";f.defer=!1;f.appendChild(e.createTextNode(d));e.body.appendChild(f);e.body.removeChild(f)}else throw Error("goog.globalEval not available");G[a]=void 0===c?b:c;return G[a]},J=function(a,
b,c,d){return(d||"http:"!=G.location.protocol?a:b)+c},ya=function(a){var b=H.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},za=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},M=function(a,b,c){var d=H.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;za(d,b);c&&(d.onerror=c);ya(d)},Aa=function(a,b){var c=H.createElement("iframe");c.height="0";c.width="0";c.style.display=
"none";c.style.visibility="hidden";ya(c);za(c,b);void 0!==a&&(c.src=a);return c},k=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},O=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},P=function(a){G.setTimeout(a,0)},Ba=!1,Da=[],Ea=function(a){if(!Ba){var b=H.createEventObject,c="complete"==H.readyState,d="interactive"==H.readyState;if(!a||"readystatechange"!=a.type||
c||!b&&d){Ba=!0;for(var e=0;e<Da.length;e++)Da[e]()}}},Fa=0,Ia=function(){if(!Ba&&140>Fa){Fa++;try{H.documentElement.doScroll("left"),Ea()}catch(a){G.setTimeout(Ia,50)}}},Ka=function(a){var b=H.getElementById(a);if(b&&Ja(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Ja(document.all[a][c],"id")==a)return document.all[a][c];return b},Ja=function(a,b){return a&&b&&a.attributes[b]?a.attributes[b].value:null},La=function(a){return a.target||a.srcElement||{}},Ma=function(a,b){for(var c={},d=0;d<
b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Na=!1,Oa=[],Pa=function(){if(!Na){Na=!0;for(var a=0;a<Oa.length;a++)Oa[a]()}},Qa=function(a){a=a||G;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)};var Ra=null,Sa=null;var Ta=new pa,Ua={},Va=ja,Wa=[],Xa=!1,$a={set:function(a,b){ia(Ya(a,b),Ua)},get:function(a){return Q(a,2)}},ab=function(a){var b=!1;return function(){!b&&w(a)&&P(a);b=!0}},hb=function(){for(var a=!1;!Xa&&0<Wa.length;){Xa=!0;var b=Wa.shift();if(w(b))try{b.call($a)}catch(c){}else if(A(b))e:{var d=b;if("string"==ea(d[0])){for(var e=d[0].split("."),f=e.pop(),g=d.slice(1),h=Ua,p=0;p<e.length;p++){if(void 0===h[e[p]])break e;h=h[e[p]]}try{h[f].apply(h,g)}catch(q){}}}else{var l=b,r=void 0;for(r in l)if(l.hasOwnProperty(r)){var n=
r,t=l[r];Ta.set(n,t);ia(Ya(n,t),Ua)}var z=!1,D=l.event;if(D){Sa=D;var v=ab(l.eventCallback),R=l.eventTimeout;R&&G.setTimeout(v,Number(R));z=Va(D,v)}if(!Ra&&(Ra=l["gtm.start"])){}Sa=null;a=z||a}var N=b,s=Ua;gb();Xa=!1}return!a},Q=function(a,b){if(2==b){for(var c=Ua,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Ta.get(a)},Ya=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var ib={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},jb={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],
nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},kb=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},cb=function(){var a=Q("gtm.whitelist"),b=a&&kb(na(a),ib),c=Q("gtm.blacklist")||Q("tagTypeBlacklist"),d=c&&kb(na(c),jb),e={};return function(f){var g=f&&f["19"];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)e:{if(0>la(b,g.a))if(g.b&&0<g.b.length)for(var p=0;p<g.b.length;p++){if(0>
la(b,g.b[p])){h=!1;break e}}else{h=!1;break e}h=!0}var q=!1;if(c){var l;if(!(l=0<=la(d,g.a)))e:{for(var r=g.b||[],n=new pa,t=0;t<d.length;t++)n.set(d[t],!0);for(t=0;t<r.length;t++)if(n.get(r[t])){l=!0;break e}l=!1}q=l}return e[g.a]=!h||q}};var _c=function(a){return a["28"]};_c.a="c";_c.b=["google"];var lb=function(a,b,c,d,e){var f=a.hash?a.href.replace(a.hash,""):a.href,g=(a.protocol.replace(":","")||G.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||G.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:G.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":var f="/"==a.pathname.substr(0,1)?a.pathname:"/"+
a.pathname,p=f.split("/");0<=la(d||[],p[p.length-1])&&(p[p.length-1]="");f=p.join("/");break;case "query":f=a.search.replace("?","");if(e)e:{for(var q=f.split("&"),l=0;l<q.length;l++){var r=q[l].split("=");if(decodeURIComponent(r[0]).replace("+"," ")==e){f=decodeURIComponent(r.slice(1).join("=")).replace("+"," ");break e}}f=void 0}break;case "fragment":f=a.hash.replace("#","")}return f},mb=function(a){var b=H.createElement("a");b.href=a;return b};var _eu=function(a){var b=String(Q("gtm.elementUrl")||a[""]||""),c=mb(b);var d,e,f;
f=a["24"];a["8"]&&(b=lb(c,a["8"],d,e,f));return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Sa};_e.a="e";_e.b=["google"];var _v=function(a){var b=Q(a["22"].replace(/\\\./g,"."),a["10"]);return void 0!==b?b:a[""]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(Q("gtm.referrer")||H.referrer),c=mb(b);return b};_f.a="f";_f.b=["google"];var nb=function(a){var b=G.location,c=b.hash?b.href.replace(b.hash,""):b.href,d;if(d=a[""]?a[""]:Q("gtm.url"))c=String(d),b=mb(c);var e,f,g;
a["8"]&&(c=lb(b,a["8"],e,f,g));return c},_u=nb;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a["3"]).indexOf(String(a["4"]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a["3"])==String(a["4"])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a["4"],a[""]?"i":void 0)).test(a["3"])};_re.a="re";_re.b=["google"];var sb=function(a,b){return a<b?-1:a>b?1:0};var tb;e:{var ub=m.navigator;if(ub){var vb=ub.userAgent;if(vb){tb=vb;break e}}tb=""}var wb=function(a){return-1!=tb.indexOf(a)};var xb=wb("Opera")||wb("OPR"),V=wb("Trident")||wb("MSIE"),yb=wb("Gecko")&&-1==tb.toLowerCase().indexOf("webkit")&&!(wb("Trident")||wb("MSIE")),zb=-1!=tb.toLowerCase().indexOf("webkit"),Ab=function(){var a=m.document;return a?a.documentMode:void 0},Eb=function(){var a="",b;if(xb&&m.opera){var c=m.opera.version;return"function"==ba(c)?c():c}yb?b=/rv\:([^\);]+)(\)|;)/:V?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:zb&&(b=/WebKit\/(\S+)/);if(b)var d=b.exec(tb),a=d?d[1]:"";if(V){var e=Ab();if(e>parseFloat(a))return String(e)}return a}(),
Fb={},W=function(a){var b;if(!(b=Fb[a])){for(var c=0,d=String(Eb).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",p=e[g]||"",q=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var r=q.exec(h)||["","",""],n=l.exec(p)||["","",""];if(0==r[0].length&&0==n[0].length)break;c=sb(0==r[1].length?0:parseInt(r[1],10),0==n[1].length?0:parseInt(n[1],10))||sb(0==r[2].length,0==n[2].length)||
sb(r[2],n[2])}while(0==c)}b=Fb[a]=0<=c}return b},Gb=m.document,Hb=Gb&&V?Ab()||("CSS1Compat"==Gb.compatMode?parseInt(Eb,10):5):void 0;if(yb||V){var Ib;if(Ib=V)Ib=V&&9<=Hb;Ib||yb&&W("1.9.1")}V&&W("9");var Jb=function(a){Jb[" "](a);return a};Jb[" "]=function(){};var Qb=function(a,b){var c="";V&&!Kb(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Lb)a.srcdoc=d;else if(Mb){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Pb(a,d)},Lb=zb&&"srcdoc"in document.createElement("iframe"),Mb=yb||zb||V&&W(11),Pb=function(a,b){V&&W(7)&&!W(10)&&6>Rb()&&Sb(b)&&(b=Tb(b));var c=function(){a.contentWindow.goog_content=
b;a.src="javascript:window.goog_content"};V&&!Kb(a)?Ub(a,c):c()},Rb=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Kb=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c){var e;if(e=null!=c.location.href)r:{try{Jb(c.foo);e=!0;break r}catch(f){}e=!1}d=e}b=d}catch(g){b=!1}return b}catch(h){return!1}},Vb=0,Ub=function(a,b){var c="goog_rendering_callback"+Vb++;window[c]=b;V&&W(6)&&!W(7)?a.src="javascript:'<script>window.onload = function() { document.write(\\'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation()})()<\\\\/script>\\');document.close();};\x3c/script>'":a.src="javascript:'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Sb=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Tb=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),
d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2013 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var bc=/(Firefox\D28\D)/g.test(xa.userAgent),dc=function(a,b,c,d){return function(e){e=e||G.event;var f=La(e),g=!1;if(3!==e.which||"CLICK"!=a&&"LINK_CLICK"!=a)if(2!==e.which&&(null!=e.which||4!=e.button)||"LINK_CLICK"!=a)if("LINK_CLICK"==a&&(f=Ma(f,["a"]),g=!f||!f.href||e.ctrlKey||e.shiftKey||e.altKey||!0===e.metaKey),e.defaultPrevented||!1===e.returnValue||e.P&&e.P()){if(!c&&f){var h={simulateDefault:!1};X(a,f,h,d)}}else{if(f){var h={},p=X(a,f,h,d),g=g||p||"LINK_CLICK"==a&&bc;h.simulateDefault=!p&&
b&&!g;h.simulateDefault&&(g=cc(f,h)||g,!g&&e.preventDefault&&e.preventDefault());e.returnValue=p||!b||g;return e.returnValue}return!0}}},X=function(a,b,c,d){var e=d||2E3,f={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Ja(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":f.event="gtm.linkClick";f["gtm.elementUrl"]=b.href;f.eventTimeout=e;f.eventCallback=ec(b,c);break;case "FORM_SUBMIT":f.event="gtm.formSubmit";var g=b.action;g&&g.tagName&&
(g=b.cloneNode(!1).action);f["gtm.elementUrl"]=g;f.eventTimeout=e;f.eventCallback=fc(b,c);break;case "CLICK":f.event="gtm.click";f["gtm.elementUrl"]=b.formAction||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return G["dataLayer"].push(f)},gc=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "form":b="_self"}return b},cc=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(xa.userAgent),e=gc(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;
f=(e||"_self").substring(1);b.targetWindow=G.frames&&G.frames[f]||G[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName="gtm_autoEvent_"+F().getTime(),b.targetWindow=G.open("",b.targetWindowName));break;default:d&&!G.frames[e]?(b.simulateDefault=!1,c=!0):(G.frames[e]||(b.targetWindowName=e),b.targetWindow=G.frames[e]||G.open("",e))}return c},ec=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||F().getTime(),500>F().getTime()-
c&&G.setTimeout(ec(a,b,c),25)))}},fc=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);H.gtmSubmitFormNow=!0;hc(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||F().getTime(),500>F().getTime()-c&&G.setTimeout(fc(a,b,c),25)}},ic=function(a,b,c,d){var e,f;switch(a){case "CLICK":if(H.gtmHasClickListenerTag)return;H.gtmHasClickListenerTag=!0;e="click";f=function(a){var b=La(a);b&&X("CLICK",b,{},d);return!0};
break;case "LINK_CLICK":if(H.gtmHasLinkClickListenerTag)return;H.gtmHasLinkClickListenerTag=!0;e="click";f=dc(a,b||!1,c||!1,d);break;case "FORM_SUBMIT":if(H.gtmHasFormSubmitListenerTag)return;H.gtmHasFormSubmitListenerTag=!0;e="submit";f=dc(a,b||!1,c||!1,d);break;default:return}O(H,e,f,!1)},hc=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;H.gtmFormElementSubmitter||(H.gtmFormElementSubmitter=
H.createElement("form"));return H.gtmFormElementSubmitter.submit.call?H.gtmFormElementSubmitter.submit:a.submit};var lc,mc;
var wc=function(a){return function(){}},xc=function(a){return function(){}};
var zc=!1,Ac=!1,_ga=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=z+b[0];n.push(b)}function e(b,c){void 0!==a[c]&&d(b,a[c])}function f(b,c){void 0!==a[c]&&d(b,Number(a[c]))}function g(a,b){if(b)for(var c=0;c<b.length;c++){var e=[a];A(b[c])?e.push.apply(e,b[c]):e.push(b[c]);"_setCustomVar"==e[0]&&void 0===e[3]||d.apply(this,e)}}function h(b,c){void 0!==a[c]&&d("_set",b,a[c])}function p(a,b){return void 0===b?b:a(b)}function q(b,c){void 0!==a[c]&&(D+="&"+b+"="+a[c])}function l(a,
b){D+="&"+a+"="+b}function r(a,b){return a.charAt(0)==b?a.substring(1):a}var n=I("_gaq",[]),t=!1,z="";void 0==a[""]?z="gtm"+va++ +".":""!==a[""]&&(z=a[""]+".");e("_setAccount","0");h("page","23");e("_setDomainName","14");
e("_setAllowLinker","2");
e("_setAllowHash","1");
var D="";
if(""!==D){var v=new pa,R=r(G.location.search,"?"),E=r(G.location.hash,"#");R&&sa(v,R);E&&a[""]&&sa(v,E);v.contains("gclid")&&l("gclid",ta(v.get("gclid")));v.contains("gclsrc")&&l("gclsrc",ta(v.get("gclsrc")));v.contains("dclid")&&l("dclid",ta(v.get("dclid")));d("_set","campaignParams",D)}
a["21"]&&d("_require","inpage_linkid","//www.google-analytics.com/plugins/ga/inpage_linkid.js");g("_setPageGroup",a["9"]);

e("_setCampaignTrack","5");
e("_setClientInfo","7");e("_setDetectFlash","12");e("_setDetectTitle","13");void 0!==a["18"]&&a["18"]&&(n.push(["_gat._forceSSL"]),t=!!a["18"]);
d("_set","hitCallback",function(){if(w(a[""]))a[""]();b()});if(a["27"]){d("_trackEvent",String(a["17"]),String(a["16"]),p(String,a[""]),p(C,a[""]),Boolean(a[""]));}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else d("_trackPageview");
var y=function(){G._gat||c()};if(a["15"])Ac||(Ac=!0,M(J("https","http","://stats.g.doubleclick.net/dc.js",t),y,c));else if(!zc){var aa=a["11"]?".google-analytics.com/u/ga_debug.js":".google-analytics.com/ga.js";zc=!0;M(J("https://ssl","http://www",aa,t),y,c)}};_ga.a="ga";_ga.b=["google"];var Fc=function(a){var b=G||m,c=b.onerror,d=!1;zb&&!W("535.3")&&(d=!d);b.onerror=function(b,f,g,h,p){c&&c(b,f,g,h,p);a({message:b,fileName:f,Sa:g,kb:h,error:p});return d}};
var Kc=function(a,b){var c=wa(a,"29",!0),d=wa(a,"6",!0),e=C(a["30"]);0>=e&&(e=2E3);ic("LINK_CLICK",!!c,!!d,e);if(!H.addEventListener){var f=function(a){a=a||G.event;for(var b=La(a);b;)b.onclick&&!b.onclick.gtmOnclickWrapper&&(b.onclick=Kc.Va(b.onclick)),b=b.parentElement};O(H,"mousedown",f,!1);O(H,"keydown",function(a){a=a||G.event;13==a.keyCode&&f(a)},!1)}P(b)};Kc.Va=function(a){var b=function(b){b=b||G.event;var d=a.call(this,
b);b.returnValue=!1!==d&&(b.returnValue||void 0===b.returnValue);return d};b.gtmOnclickWrapper=!0;return b};var _lcl=Kc;_lcl.a="lcl";var gd=function(){this.f=[]};gd.prototype.set=function(a,b){this.f.push([a,b]);return this};gd.prototype.resolve=function(a,b){for(var c={},d=0;d<this.f.length;d++){var e=hd(this.f[d][0],a,b),f=hd(this.f[d][1],a,b);c[e]=f}return c};var id=function(a){this.index=a};id.prototype.resolve=function(a,b){var c=db[this.index];if(c&&!b(c)){var d=c["20"];if(a){if(a.get(d))return;a.set(d,!0)}c=hd(c,a,b);a&&a.set(d,!1);return qa(c)}};
for(var _M=function(a){return new id(a)},kd=function(a){this.resolve=function(b,c){for(var d=[],e=0;e<a.length;e++)d.push(hd(jd[a[e]],b,c));return d.join("")}},_T=function(a){return new kd(arguments)},ld=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.resolve=function(c,d){if(a[0]instanceof id&&b(8)&&b(16))return'google_tag_manager["GTM-T6Q59G"].macro('+a[0].index+")";for(var e=String(hd(a[0],c,d)),f=1;f<a.length;f++)e=Z[a[f]](e);return e}},_E=function(a,b){return new ld(arguments)},fb=function(a,b){return hd(a,new pa,b)},hd=function(a,b,c){var d=a;if(a instanceof id||a instanceof gd||a instanceof kd||
a instanceof ld)return a.resolve(b,c);if(A(a))for(var d=[],e=0;e<a.length;e++)d[e]=hd(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=hd(a[f],b,c))}return d},md=function(a,b){var c=b[a],d=c;if(c instanceof id||c instanceof ld||c instanceof kd)d=c;else if(A(c))for(var d=[],e=0;e<c.length;e++)d[e]=md(c[e],b);else if("object"==typeof c){var d=new gd,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],md(c[f],b))}return d},pd=function(a,b){for(var c=b?b.split(","):[],
d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=jd[e[1]]);if(1==a)for(var f=nd(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=od[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=nd(e[g])}return c},nd=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<qd;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f=0,f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},
qd=73,rd=[_re,_u,'url',_M(0),'.*',_eq,_e,'_event',_M(1),'gtm.js',_lcl,'Link Click Listener',true,false,'2000',3,_ga,'GA QA Test',_c,'Ynet QA GA','UA-10772561-7',_M(2),_v,'pageName',2,_M(3),'.ynet.co.il',[],_cn,'event',_M(4),'gtm.linkClick','element url','gtm.elementUrl',_M(5),'shop','GA Partners Events',_eu,'ynet_partner','query','utm_content',_M(6),'Partners',4,'url path','path','url hostname','host','element classes','gtm.elementClasses','element','gtm.element',_f,'referrer','element target','gtm.elementTarget','element id','gtm.elementId','Full URL'],sd=[],td=0;td<rd.length;td++)sd[td]=md(td,rd);var jd=sd,od=pd(0,"19:0,19:1,20:2,3:3,4:4,19:5,19:6,20:7,3:8,4:9,19:10,20:11,29:12,6:13,30:14,26:15,19:16,20:17,19:18,20:19,28:20,0:21,19:22,20:23,22:23,10:24,23:25,14:26,2:12,1:13,15:12,21:13,9:27,5:12,7:12,12:12,13:12,25:12,11:13,18:13,26:24,19:28,20:29,3:30,4:31,20:32,22:33,3:34,4:35,20:36,27:12,19:37,20:38,8:39,24:40,16:41,17:42,26:43,20:44,8:45,20:46,8:47,20:48,22:49,20:50,22:51,19:52,20:53,20:54,22:55,20:56,22:57,20:58"),db=pd(1,"G,AD,AAAH,AAAwD,ABAAAAAB,AAAQAAAY,AAAAAAAA4B,CAAAAAAAAw,CAAAAAAAAAD,AAAQAAAAAAM,AAAQAAAAAAw,AAAAAAAAAAAD,AAAQAAAAAAAM,AAAQAAAAAAAw,CAAAAAAAAgAAB"),ud=pd(1,"Z,gM,AAAAAAgG,AAAAAAggB"),$=pd(1,"AwP,AAwI8_f,AAQIA_PAGO"),vd=pd(2,"D:D::,M:E::");
var gb=function(){};var Jd=function(){var a=this;this.t=!1;this.w=[];this.K=[];this.la=function(){a.t||ua(a.w);a.t=!0};this.ka=function(){a.t||ua(a.K);a.t=!0};this.L=ja},Kd=function(){this.j=[];this.Z={};this.M=[];this.o=0};Kd.prototype.addListener=function(a){this.M.push(a)};var Ld=function(a,b,c,d){if(!c.t){a.j[b]=c;void 0!==d&&(a.Z[b]=d);a.o++;var e=function(){0<a.o&&a.o--;0<a.o||ua(a.M)};c.w.push(e);c.K.push(e)}};var Md=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=ud[b]&&fb(ud[b],c);a[b]=[d&&qa(d),d]}return a[b]}},Nd=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.d(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.d(e[d],a.c)[0])return!1;return!0},Od=function(a,b){return function(){a["31"]=b.la;a["32"]=b.ka;qa(a,b.la,b.ka)}},Va=function(a,b){Q("tagTypeBlacklist");for(var c={name:a,Ea:b||ja,p:nd(),r:nd(),d:Md(),c:cb()},d=0;d<vd.length;d++)if(Nd(c,
vd[d])){for(var e=c,f=vd[d],g=f[1],h=0;h<g.length;h++)e.p[g[h]]=!0;for(var p=f[3],h=0;h<p.length;h++)e.r[p[h]]=!0}var q=[];for(var l=0;l<qd;l++)if(c.p[l]&&!c.r[l])if(c.c($[l])){}else{q[l]=fb($[l],c.c);}c.A=q;for(var r=
new Kd,n=0;n<qd;n++)if(c.p[n]&&!c.r[n]&&!c.c($[n])){var t=c.A[n],z=new Jd;z.w.push(wc(t));z.K.push(xc(t));z.L=Od(t,z);Ld(r,n,z,t[""])}r.addListener(c.Ea);for(var D=[],v=0;v<r.j.length;v++){var R=r.j[v];if(R){var E=r.Z[v];void 0!==E?E!=v&&r.j[E]&&r.j[E].w.push(R.L):D.push(v)}}for(v=0;v<D.length;v++)r.j[D[v]].L();0<r.o||ua(r.M);return 0<c.A.length};var Pd={macro:function(a){return db[a]&&fb(_M(a),cb())}};Pd.dataLayer=$a;Pd.Ta=function(){var a=G.google_tag_manager;a||(a=G.google_tag_manager={});a["GTM-T6Q59G"]||(a["GTM-T6Q59G"]=Pd)};Pd.Ta();
(function(){var a=I("dataLayer",[]),b=I("google_tag_manager",{}),b=b["dataLayer"]=b["dataLayer"]||{};Da.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Oa.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Wa.push.apply(Wa,b);300<this.length;)this.shift();return hb()};Wa.push.apply(Wa,a.slice(0));P(hb)})();
if("interactive"==H.readyState&&!H.createEventObject||"complete"==H.readyState)Ea();else{O(H,"DOMContentLoaded",Ea);O(H,"readystatechange",Ea);if(H.createEventObject&&H.documentElement.doScroll){var Qd=!0;try{Qd=!G.frameElement}catch(Sd){}Qd&&Ia()}O(G,"load",Ea)}"complete"===H.readyState?Pa():O(G,"load",Pa);var _vs="res_ts:1399902131587000,srv_cl:66074325,ds:live,cv:9";
})()
