var Exposebox={config:{path:window.location.protocol+"//server.exposebox.com",files:"http:"===window.location.protocol?"sf.exposebox.com":"exposebox.blob.core.windows.net",MAX_RESULTS:0},jQueryLoad:function(){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=window.location.protocol+"//"+this.config.files+"/widget/exposebox-jquery.js?v=1.00";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)},stringToXML:function(b){if(window.ActiveXObject||
"ActiveXObject"in window){var a=new ActiveXObject("Microsoft.XMLDOM");a.async="false";a.loadXML(b)}else a=(new DOMParser).parseFromString(b,"text/xml");return a},xslToHtml:function(b,a){if(window.ActiveXObject||"ActiveXObject"in window)var d=b.transformNode(a);else document.implementation&&document.implementation.createDocument&&(d=new XSLTProcessor,d.importStylesheet(a),d=d.transformToFragment(b,document));return d},jQueryLoaded:function(b){Exposebox.interval||(Exposebox.interval=setInterval(Exposebox.waitForWidget,
50));this.waitForWidget()},loadXMLDoc:function(b){xhttp=window.ActiveXObject||"ActiveXObject"in window?new ActiveXObject("Msxml2.XMLHTTP.3.0"):new XMLHttpRequest;xhttp.open("GET",b,!1);xhttp.send("");return xhttp.responseXML},waitForWidget:function(){var b=Exposebox.jQuery;Exposebox.widget=b("#exposebox-widget");Exposebox.widget[0]||(Exposebox.widget=b("#exposebox-widget-extension"));ExposeboxLayout&&ExposeboxLayout.isReady&&b.isReady&&(Exposebox.interval=clearInterval(Exposebox.interval),Exposebox.widget[0]?
Exposebox.start():Exposebox.isReady=!0)},markBuy:function(b,a,d){Exposebox.jQuery.ajax({type:"GET",url:Exposebox.config.path+"/refdir",scriptCharset:"utf-8",dataType:"jsonp",data:{url:"http"===b.substring(0,4)?b:window.location.protocol+"//"+window.location.host+b,buy:"T",conversion:a,conversionId:d},timeout:2E3})},htmlDecode:function(b){return b.replace(RegExp("&amp;","g"),"&").replace(RegExp("&quot;","g"),'"').replace(RegExp("&lt;","g"),"<").replace(RegExp("&gt;","g"),">")},fromJsonToXmlString:function(b){try{var a=
this.jQuery.parseJSON(b)}catch(d){return b}b="";for(var c in a)b+="<"+c+">"+a[c]+"</"+c+">";return b},start:function(){var b=Exposebox.jQuery,a=Exposebox.widget.attr("data-layout"),d=ExposeboxLayout[a];Exposebox.layout=d;Exposebox.paramTitle=Exposebox.widget.attr("data-text1")||d.getTitle&&d.getTitle()||window.document.title;Exposebox.paramSubtitle=Exposebox.widget.attr("data-text2");var a=Exposebox,c;(c=Exposebox.widget.attr("data-category"))||(c=d.categoryParser?d.categoryParser():void 0);a.paramCategory=
c;Exposebox.paramType=Exposebox.widget.attr("data-type");a=function(a){return d.urlParser?d.urlParser(a):a};Exposebox.paramURL=Exposebox.widget.attr("data-url")||a(window.location.href);if(a=Exposebox.widget.attr("data-url-d"))Exposebox.paramURL=document.referrer||a,Exposebox.paramSubtitle||(Exposebox.paramSubtitle=Exposebox.paramURL);(a=Exposebox.widget.attr("data-show")||!1)&&(a="true"===a.toLowerCase());c=Exposebox.widget.attr("debug")||!1;Exposebox.paramImageUrl=Exposebox.widget.attr("data-image-url");
Exposebox.paramPrice=Exposebox.widget.attr("data-text3");Exposebox.paramShipping=Exposebox.widget.attr("data-text4");Exposebox.paramPayment=Exposebox.widget.attr("data-text5");Exposebox.paramRating=Exposebox.widget.attr("data-rating");Exposebox.paramPaymentSmall=Exposebox.widget.attr("data-text6");var g=d.isOpen&&d.isOpen()||Exposebox.widget.attr("data-sale-open")||"T",f=Exposebox.widget.attr("data-free-json");f&&(Exposebox.paramDataFreeJson=Exposebox.htmlDecode(f));Exposebox.paramUK=Exposebox.widget.attr("data-uk");
Exposebox.paramUrlSuffix=Exposebox.widget.attr("data-url-suffix")||"";Exposebox.paramUrlSuffixMode=Exposebox.widget.attr("data-url-suffix-m");Exposebox.paramUrlSuffixB=Exposebox.widget.attr("data-url-suffix-b");Exposebox.paramUrlPrefix=Exposebox.widget.attr("data-url-prefix");Exposebox.paramImpTrack=Exposebox.widget.attr("data-imp-track");Exposebox.paramClickTrack=Exposebox.widget.attr("data-click-track");Exposebox.paramKeepMerchants="true"===(Exposebox.widget.attr("data-keep")||"").toLowerCase();
Exposebox.paramXsl=Exposebox.widget.attr("data-xsl");var h=Exposebox.widget.attr("data-recommendations-num");(f=Exposebox.widget.attr("paging")||!1)&&(f="true"===f.toLowerCase());h&&(Exposebox.layout.MAX_RESULTS=parseInt(h,10));Exposebox.paramSaleOpen=g.charAt(0).toUpperCase();if(c||0<=window.location.href.indexOf("exposebox=debug")||0<=document.referrer.indexOf("exposebox=debug"))Exposebox.config.path=window.location.protocol+"//localhost:65025";a||0<=window.location.href.indexOf("exposebox=show")||
0<=document.referrer.indexOf("exposebox=show")?Exposebox.widget.show():Exposebox.widget.hide();Exposebox.runAfterLoad=Exposebox.widget.attr("data-onload");var k=function(a,e){if(a&&!(0>=a.length)){var c=Exposebox.createHtml(a,Exposebox.layout.MAX_RESULTS,e),d=Exposebox.layout.MAX_RESULTS;Exposebox.widget.html(c);Exposebox.paramImpTrack&&b.get(Exposebox.paramImpTrack,function(){});Exposebox.addOnClick(Exposebox.widget);if(Exposebox.extensions)for(c=0;c<Exposebox.extensions.length;c++){var f=Exposebox.extensions[c],
g=f.maxResults,h=Exposebox.createHtml(a.splice(d,a.length),g,e,f),d=d+g,f=b(f.widget);f.html(h);Exposebox.addOnClick(f)}Exposebox.runAfterLoad&&eval(Exposebox.runAfterLoad);if(Exposebox.extensions)for(c=0;c<Exposebox.extensions.length;c++)f=Exposebox.extensions[c],eval(f.runAfterLoad)}};if(Exposebox.paramUrlSuffixB||d.abTesting)Exposebox.fullRes=!0;a=function(){var a=(Exposebox.layout.url||Exposebox.config.path)+"/MerchantsService.svc/GetMerchants",b=Exposebox.layout.MAX_RESULTS;if(Exposebox.extensions)for(var c=
0;c<Exposebox.extensions.length;c++)b+=Exposebox.extensions[c].maxResults;Exposebox.fetchMerchants(a,{maxResults:b},function(a){Exposebox.fullRes?(Exposebox.paramKeepMerchants&&(Exposebox.keep=a.merchants.slice(0)),k(a.merchants,a.abt)):(Exposebox.paramKeepMerchants&&(Exposebox.keep=a.slice(0)),k(a))})};this.readExtension();f||a();this.isReady=!0},readExtension:function(){var b=Exposebox.jQuery,a=b("#exposebox-widget-extension");if(!(!a&&1>a.length||a[0]===this.widget[0])){Exposebox.extensions=[];
for(var d=0;d<a.length;d++){var c={widget:b(a[d])};Exposebox.extensions[0]=c;var g=ExposeboxLayout[c.widget.attr("data-layout")];c.layout=g;g=b(c.widget).attr("data-recommendations-num");c.maxResults=g?parseInt(g,10):c.layout.MAX_RESULTS;c.paramXsl=c.widget.attr("data-xsl");c.runAfterLoad=c.widget.attr("data-onload")}}},getPage:function(b,a,d){Exposebox.fetchMerchants((Exposebox.layout.url||Exposebox.config.path)+"/getPage",{start:b,num:a},function(a){return d(a)})},isReady:!1,createHtmlFromXls:function(b,
a,d){return Exposebox.keep?"exposebox-widget-extension"===d?this.createHtml(Exposebox.keep.slice(Exposebox.layout.MAX_RESULTS),a,1,{layout:ExposeboxLayout.XSLT,paramXsl:b}):this.createHtml(Exposebox.keep.slice(0),a,1,{layout:ExposeboxLayout.XSLT,paramXsl:b}):null},createHtml:function(b,a,d,c){c||(c=Exposebox);d||(d=1);for(var g=c.layout.abTesting?c.layout.layouts[d]:c.layout,f=g.finalHtml,h=g.template,g=g.endHtml,k=0,n=0;n<b.length&&n<a+k;n++){var e=b[n];if(Exposebox.paramURL===e.url||Exposebox.paramTitle===
e.title&&Exposebox.paramSubtitle===e.subtitle&&Exposebox.paramPrice===e.price&&Exposebox.paramShipping===e.shipping&&Exposebox.paramPayment===e.payment&&Exposebox.paramPaymentSmall===e.payment_small&&Exposebox.paramRating===e.rating&&Exposebox.paramImageUrl===e.image_url)k++;else{Exposebox.paramUrlSuffixB&&d&&2==d&&(Exposebox.paramUrlSuffix=Exposebox.paramUrlSuffixB);e.url&&0<Exposebox.paramUrlSuffix.length&&(Exposebox.paramUrlSuffixMode&&"as_is"===Exposebox.paramUrlSuffixMode?e.url+=Exposebox.paramUrlSuffix:
Exposebox.paramUrlSuffixMode&&"ae"===Exposebox.paramUrlSuffixMode?"="===e.url.slice(-1)&&(e.url+=Exposebox.paramUrlSuffix):0<e.url.indexOf("?")?e.url=e.url+"&"+Exposebox.paramUrlSuffix:e.url=e.url+"?"+Exposebox.paramUrlSuffix);e.url&&Exposebox.paramUrlPrefix&&0<Exposebox.paramUrlPrefix.length&&(e.url=Exposebox.paramUrlPrefix+encodeURIComponent(e.url));Exposebox.merchants[e.url]={id:e.id,type_id:e.type_id};c.layout.alterImageUrl&&(e.image_url=c.layout.alterImageUrl(e.image_url));if(e.free_data)if(c.paramXsl)e.free_data=
Exposebox.fromJsonToXmlString(e.free_data);else if(c.layout.parseJson)try{var l=JSON.parse(e.free_data),p;for(p in l)e["fd_"+p]=l[p]}catch(q){}var m="string"==typeof h||h instanceof String?h:h[e.type_id];for(key in e)e[key]&&(m=m.replace(RegExp("{{"+key+"}}","g"),e[key]));if(e.free_data&&!c.paramXsl)try{for(key in l=JSON.parse(e.free_data),l)l[key]&&(m=m.replace(RegExp("{{"+key+"}}","g"),l[key]))}catch(r){}f+=m}}f=(f+g).replace(RegExp("{{.+?}}","g"),"");c.paramXsl&&(b=Exposebox.stringToXML(f.replace(RegExp("&",
"g"),"&amp;")),c=Exposebox.loadXMLDoc(c.paramXsl),f=Exposebox.xslToHtml(b,c));return f},fetchMerchants:function(b,a,d){var c="c"+Math.floor(1E8*Math.random()+1);a||(a={});a.subtitle=Exposebox.paramSubtitle;a.category=Exposebox.paramCategory;a.type=Exposebox.paramType;a.url=Exposebox.paramURL;a.title=Exposebox.paramTitle;a.imageUrl=Exposebox.paramImageUrl;a.price=Exposebox.paramPrice;a.shipping=Exposebox.paramShipping;a.payment=Exposebox.paramPayment;a.rating=Exposebox.paramRating;a.paymentSmall=Exposebox.paramPaymentSmall;
a.saleOpen=Exposebox.paramSaleOpen;a.fullRes=Exposebox.fullRes;a.freeData=Exposebox.paramDataFreeJson;a.uk=Exposebox.paramUK;Exposebox.jQuery.ajax({type:"GET",url:b,scriptCharset:"utf-8",dataType:"jsonp",data:a,timeout:1E4,jsonpCallback:c,success:d})},notifyOnClick:function(b,a,d,c){var g=b.currentTarget.href,f=Exposebox.merchants[g],h=!(Exposebox.layout&&Exposebox.layout.openNew||a);h&&b.preventDefault();if(Exposebox.paramClickTrack&&!d){var k=!1;b=new Image;b.src=Exposebox.paramClickTrack;a=function(){k=
!0};b.onload=a;b.onerror=a;b.onabort=a}Exposebox.jQuery.ajax({type:"GET",url:Exposebox.config.path+"/refdir",scriptCharset:"utf-8",dataType:"jsonp",data:{url:g,fromUrl:Exposebox.paramURL,type_id:f&&f.type_id,id:f&&f.id,buy:c},timeout:2E3,complete:function(a,b){if(h)if(Exposebox.paramClickTrack)if(k)window.top.location.href=g;else var c=0,d=setInterval(function(){if(k||4<c)window.top.location.href=g,clearInterval(d);c++},100);else window.top.location.href=g}})},addOnClick:function(b){b.on("click",
"a",Exposebox.notifyOnClick);b.on("mouseup","a",function(a){2==a.which&&Exposebox.notifyOnClick(a,!0);3==a.which&&Exposebox.notifyOnClick(a,!0,!1,"R")})},logViewRecommendations:function(b){for(var a=0;a<b.length;a++)Exposebox.jQuery.ajax({type:"get",url:Exposebox.config.path+"/logRecommendationView",data:{url:Exposebox.paramURL,type:Exposebox.paramType,recommendedUrl:b[a].url,recommendedType:b[a].type_id,recommendedId:b[a].id},contentType:"application/json; charset=utf-8",dataType:"jsonp",success:function(a,
b){}})},merchants:[],pop:function(b){if(b=this.createHtmlFromXls(b,1)){var a=Exposebox.jQuery;a("body").append('<div id="exposebox-pop" style="position:fixed; float:right; bottom:2px; right:0px; z-index:10000; display:none "></div>');a("#exposebox-pop").append(b);a("#exposebox-pop").append('<button id="exposebox-pop-close" style="position:absolute;top:10px;left:10px;">X</button>');a("#exposebox-pop-close").click(function(){a("#exposebox-pop").animate({height:"toggle"},500)});a("#exposebox-pop").animate({height:"toggle"},
1E3,function(){})}}};(function(){Exposebox.jQueryLoad()})();